### ISSUE TITLE
Team RoboTutor: Fix incorrect serial numbers in tablet tracker

### ISSUE THREAD

**Issue by jo-xprize** [XPRIZE/glexp-data-standardization#40]
- [x] Convert from lower-case to upper-case letters in tablet serial numbers.
- [x] Identify serial numbers found in tablet usage data, but not in tracker
- [x] Identify serial numbers found in tracker, but not in tablet usage data
- [ ] Correct typos in serial numbers.
